openapi: 3.0.3
info:
  title: Miner API
  description: |-
    This section is still a WIP and is incomplete. The Miner node is most like the Bitcoin miner you may be familiar with. They are responsible for mining new blocks that they receive from the Mempool nodes and collect the associated block reward for their efforts. They are only able to mine a block if they manage to get into the partition for that round.
  contact:
    email: byron.houwens@a-block.net
  license:
    name: GPL-3.0
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: 1.0.0
externalDocs:
  description: Find out more about ABlock
  url: https://a-block.net
servers:
  - url: http://49.12.234.10:3000
    description: Testnet Miner Node
tags:
  - name: info
    description: Getting information about and from the node.
  - name: wallet
    description: All calls associated with a wallet.
paths:
  /debug_data:
    get:
      tags:
        - info
      summary: debug_data
      description: Get general information about the current node.
      operationId: debugData
      parameters:
        - in: header
          name: x-cache-id
          required: true
          description: An idempotent key for retrieving cached responses from the node
          schema:
            type: string
            example: "fde57c5d0e0c49f8a9e91ba5acc18cfd"
            pattern: ^[a-z0-9]{32}$
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseDebugData"
components:
  schemas:
    ResponseDebugData:
      type: object
      properties:
        id:
          type: string
          example: "fde57c5d0e0c49f8a9e91ba5acc18cfd"
          description: The ID of the call, which corresponds to the x-cache-id used in the header
        status:
          type: string
          example: "Success"
          description: The status of the call, which will be one of either "Success", "Error", or "Pending"
        reason:
          type: string
          example: "Debug data successfully retrieved"
          description: The reason for the status of the call. Most useful to debug errors
        route:
          type: string
          example: "debug_data"
          description: The endpoint route that was called
        content:
          type: object
          properties:
            node_type:
              type: string
              example: "Compute"
              description: The type of this node
            node_api:
              type: array
              description: The publicly visible endpoints available on this node
              items:
                type: string
              example:
                - fetch_balance
                - create_item_asset
                - create_transactions
            node_peers:
              type: array
              description: The publicly visible nodes that this node is connected to
              items:
                type: string
              example:
                - "Storage"
            routes_pow:
              type: object
              properties:
                create_transactions:
                  type: number
                  example: 2